name: Deploy Frontend to S3

on:
  push:
    tags:
      - "v*.*.*"

  # For debugging workflow manually
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

permissions:
  id-token: write
  contents: read

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.GHA_ROLE_FOR_DEPLOYING_FRONTEND }}

      - name: Install Dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Sync with S3 Bucket
        run: aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }}
